# Generated by Django 6.0 on 2025-12-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GolfItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CLUB', 'Golf Club'), ('POSTER', 'Poster'), ('PICTURE', 'Picture')], max_length=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='golf_images/')),
            ],
        ),
    ]
